-- Auto-generated DDL for Fabric Warehouse table
-- Source: Dataiku dataset "${dataset_name}"
-- Generated by DataikuToFabric toolkit

CREATE TABLE [dbo].[${table_name}] (
    -- Columns will be generated from Dataiku schema
    ${columns}
);
